<?php
    $momentPerTour = array();
    if(count($_FILES) > 0)
    {
        $content = json_decode(file_get_contents($_FILES['file']['tmp_name']),true);
        $playersList = $content["Players"];
    }
    

    function getDataByType($type)
    {
        $array = array(
            "MOMENT_FIND_NEW_CONTINENT_FIRST_IN_WORLD" => array("color" => "success","traduction" => "Découverte","icon" => "earth-europe"),
            "MOMENT_CITY_BUILT_NEAR_FLOODABLE_RIVER" => array("color" => "warning","traduction" => "Civilisation","icon" => "city"),
            "MOMENT_CITY_BUILT_NEAR_VOLCANO" => array("color" => "warning","traduction" => "Civilisation","icon" => "city"),
            "MOMENT_GOODY_HUT_TRIGGERED" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_BATTLE_FOUGHT" => array("color" => "danger","traduction" => "Bataille","icon" => "gun"),
            "MOMENT_PLAYER_MET_MAJOR" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_BARBARIAN_CAMP_DESTROYED" => array("color" => "danger","traduction" => "Bataille","icon" => "gun"),
            "MOMENT_FIND_NATURAL_WONDER_FIRST_IN_WORLD" => array("color" => "success","traduction" => "Découverte","icon" => "earth-europe"),
            "MOMENT_PLAYER_GAVE_ENVOY_BECAME_SUZERAIN_FIRST_IN_WORLD" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_PANTHEON_FOUNDED_FIRST_IN_WORLD" => array("color" => "secondary","traduction" => "Religion","icon" => "hands-praying"),
            "MOMENT_PANTHEON_FOUNDED" => array("color" => "secondary","traduction" => "Religion","icon" => "hands-praying"),
            "MOMENT_BARBARIAN_CAMP_DESTROYED_NEAR_YOUR_CITY" => array("color" => "danger","traduction" => "Bataille","icon" => "gun"),
            "MOMENT_PLAYER_LEVIED_MILITARY" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_DISTRICT_CONSTRUCTED_HIGH_ADJACENCY_CAMPUS" => array("color" => "warning","traduction" => "Civilisation","icon" => "bottle-droplet"),
            "MOMENT_UNIT_CREATED_FIRST_DOMAIN_SEA_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "anchor"),
            "MOMENT_HERO_CREATED_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "crown"),
            "MOMENT_BUILDING_CONSTRUCTED_GAME_ERA_WONDER" => array("color" => "success","traduction" => "Découverte","icon" => "earth-europe"),
            "MOMENT_CITY_BUILT_NEAR_OTHER_CIV_CITY" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_CITY_BUILT_NEW_CONTINENT" => array("color" => "warning","traduction" => "Civilisation","icon" => "city"),
            "MOMENT_TECH_RESEARCHED_IN_ERA_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "people"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_ON_DISASTER_YIELD_TILE_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "city"),
            "MOMENT_GREAT_PERSON_CREATED_GAME_ERA" => array("color" => "warning","traduction" => "Personnage illustre","icon" => "person"),
            "MOMENT_CITY_BUILT_ON_TUNDRA" => array("color" => "warning","traduction" => "Civilisation","icon" => "city"),
            "MOMENT_GAME_ERA_STARTED_WITH_NORMAL_AGE" => array("color" => "warning","traduction" => "Civilization","icon" => "earth-europe"),
            "MOMENT_GAME_ERA_STARTED_WITH_DARK_AGE" => array("color" => "warning","traduction" => "Civilization","icon" => "earth-europe"),
            "MOMENT_UNIT_CREATED_FIRST_REQUIRING_STRATEGIC_IN_WORLD" => array("color" => "warning","traduction" => "Civilization","icon" => "earth"),
            "MOMENT_BUILDING_CONSTRUCTED_PAST_ERA_WONDER" => array("color" => "warning","traduction" => "Civilization","icon" => "earth"),
            "MOMENT_RELIGION_FOUNDED_FIRST_IN_WORLD" => array("color" => "secondary","traduction" => "Religion","icon" => "hands-praying"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_1_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilization","icon" => "earth-europe"),
            "MOMENT_CIVIC_CULTURVATED_IN_ERA_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilization","icon" => "earth-europe"),
            "MOMENT_CIVIC_CULTURVATED_IN_ERA_FIRST" => array("color" => "warning","traduction" => "Civilization","icon" => "earth-europe"),
            "MOMENT_PLAYER_GAVE_ENVOY_CANCELED_LEVY" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_CITY_TRANSFERRED_PLAYER_DEFEATED" => array("color" => "danger","traduction" => "Guerre","icon" => "gun"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_1_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_CREATED_FIRST_DOMAIN_SEA" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_DISTRICT_CONSTRUCTED_HIGH_ADJACENCY_HARBOR" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_CREATED_FIRST_REQUIRING_STRATEGIC" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FIRST_INDUSTRY_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_HERO_EXPIRED_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_DISTRICT_CONSTRUCTED_HIGH_ADJACENCY_COMMERCIAL_HUB" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_TRADING_POST_CONSTRUCTED_IN_OTHER_CIV" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_DISTRICT_CONSTRUCTED_HIGH_ADJACENCY_HOLY_SITE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_SMALL_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_DISTRICT_CONSTRUCTED_HIGH_ADJACENCY_THEATER_SQUARE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GREAT_PERSON_CREATED_PATRONAGE_FAITH_OVER_HALF" => array("color" => "secondary","traduction" => "Religion","icon" => "hands-praying"),
            "MOMENT_DISTRICT_CONSTRUCTED_FIRST_UNIQUE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_RELIGION_FOUNDED" => array("color" => "secondary","traduction" => "Religion","icon" => "hands-praying"),
            "MOMENT_TECH_RESEARCHED_IN_ERA_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_SMALL_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FIND_NATURAL_WONDER" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GAME_ERA_STARTED_WITH_GOLDEN_AGE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FIRST_LUXURY_RESOURCE_MONOPOLY_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PLAYER_LEVIED_MILITARY_NEAR_ENEMY_CITY" => array("color" => "danger","traduction" => "Guerre","icon" => "gun"),
            "MOMENT_GREAT_PERSON_CREATED_PAST_ERA" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_SHIP_SUNK" => array("color" => "danger","traduction" => "Guerre","icon" => "gub"),
            "MOMENT_HERO_CREATED" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_BUILT_ON_DESERT" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_MEDIUM_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FIRST_INDUSTRY" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_MEDIUM_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_FIRST_UNIQUE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FIRST_LUXURY_RESOURCE_MONOPOLY" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_DISTRICT_CONSTRUCTED_HIGH_ADJACENCY_INDUSTRIAL_ZONE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_CREATED_FIRST_UNIQUE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_KILLED_ASSISTED_BY_GENERAL" => array("color" => "danger","traduction" => "Bataille","icon" => "gun"),
            "MOMENT_MITIGATED_RIVER_FLOOD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_CHANGED_RELIGION_ENEMY_CITY_DURING_WAR" => array("color" => "secondary","traduction" => "Religion","icon" => "hands-praying"),
            "MOMENT_PLAYER_GAVE_ENVOY_CANCELED_SUZERAIN_DURING_WAR" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_HERO_EXPIRED" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_2_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_LARGE_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PLAYER_MET_ALL_MAJORS_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_2_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_BUILDING_CONSTRUCTED_FIRST_UNIQUE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FORMATION_CORPS_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_HERO_RECALLED_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_BUILT_NEAR_NATURAL_WONDER" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_LARGE_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FORMATION_CORPS_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_DISTRICT_CONSTRUCTED_NEIGHBORHOOD_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_TRANSFERRED_TO_ORIGINAL_OWNER" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_DISTRICT_CONSTRUCTED_NEIGHBORHOOD_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_BUILDING_CONSTRUCTED_FULL_ENCAMPMENT_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_POWER_GENERATED_FROM_RESOURCE_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_BELIEF_ADDED_MAX_BELIEFS_REACHED_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_HERO_RECALLED" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FORMATION_FLEET_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FORMATION_ARMY_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNOR_FULLY_PROMOTED_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_DISTRICT_CONSTRUCTED_CANAL" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GAME_ERA_STARTED_WITH_HEROIC_AGE" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FORMATION_ARMY_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_POWER_GENERATED_FROM_RESOURCE_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_3_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNOR_ALL_APPOINTED_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_KILLED_UNDERDOG_MILITARY_FORMATION" => array("color" => "danger","traduction" => "Bataille","icon" => "gun"),
            "MOMENT_WORLD_CIRCUMNAVIGATED_FIRST_IN_WORLD" => array("color" => "success","traduction" => "Découverte","icon" => "earth"),
            "MOMENT_BELIEF_ADDED_MAX_BELIEFS_REACHED" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_3_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_BUILT_ON_SNOW" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_ARTIFACT_EXTRACTED" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_EXTRA_LARGE_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_SEASIDE_RESORT_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_SPY_MAX_LEVEL_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_SIZE_EXTRA_LARGE_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PLAYER_MET_ALL_MAJORS" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_BUILDING_CONSTRUCTED_FULL_WATER_ENTERTAINMENT_COMPLEX_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_BUILDING_CONSTRUCTED_FULL_AERODROME_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_BUILDING_CONSTRUCTED_FULL_ENTERTAINMENT_COMPLEX_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_MOUNTAIN_TUNNEL_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_ROUTE_CREATED_RAILROAD_CONNECTS_TWO_CITIES_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_WORLD_CIRCUMNAVIGATED" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_ROUTE_CREATED_RAILROAD_CONNECTS_TWO_CITIES" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_MOUNTAIN_TUNNEL_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CLIMATE_CHANGE_PHASE" => array("color" => "success","traduction" => "Climat","icon" => "earth"),
            "MOMENT_FORMATION_ARMADA_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_MANHATTEN" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_SATELLITE_LAUNCH_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_4_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_MOON_LANDING_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_MITIGATED_COASTAL_FLOOD" => array("color" => "success","traduction" => "Climat","icon" => "earth"),
            "MOMENT_UNIT_CREATED_FIRST_DOMAIN_AIR_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_CREATED_FIRST_DOMAIN_AIR" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_SEASIDE_RESORT_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_OPERATION_IVY" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_GOVERNMENT_ENACTED_TIER_4_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_MARS_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_INQUISITION_LAUNCHED_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_ARTIFACT_EXTRACTED_SHIPWRECK_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_RENEWABLE_ENERGY_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_EXOPLANET_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FORMATION_FLEET_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_SATELLITE_LAUNCH" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_IMPROVEMENT_CONSTRUCTED_RENEWABLE_ENERGY_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_KILLED_UNDERDOG_PROMOTIONS" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_FORMATION_ARMADA_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_EMERGENCY_WON_AS_MEMBER" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_TOURISM_BOMB_FIRST_IN_WORLD" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_CITY_TRANSFERRED_FOREIGN_CAPITAL" => array("color" => "info","traduction" => "Diplomatie","icon" => "handshake-simple"),
            "MOMENT_PROJECT_FOUNDED_MOON_LANDING" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_TOURISM_BOMB" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_MARS" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_PROJECT_FOUNDED_EXOPLANET" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_EMERGENCY_WON_AS_TARGET" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_HIGH_LEVEL_FIRST" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
            "MOMENT_UNIT_KILLED_ASSISTED_BY_ADMIRAL" => array("color" => "danger","traduction" => "Bataille","icon" => "gun"),
            "MOMENT_UNIT_HIGH_LEVEL" => array("color" => "warning","traduction" => "Civilisation","icon" => "earth"),
        );
        if(isset($array[$type]))
        {
            return $array[$type];
        }else{
            return("unknown");
        }
    }

    function getEraById($eraId)
    {
        $array = array(
            "ERA_ANCIENT" => array("libelle" => "Ére ancienne","icon" => "house"),
            "ERA_CLASSICAL" => array("libelle" => "Ére classique","icon" => "gopuram"),
            "ERA_MEDIEVAL" => array("libelle" => "Ére médiévale","icon" => "castle"),
            "ERA_RENAISSANCE" => array("libelle" => "Ére de la renaissance","icon" => "castle"),
            "ERA_INDUSTRIAL" => array("libelle" => "Ére industrielle","icon" => "industry"),
            "ERA_MODERN" => array("libelle" => "Ére moderne","icon" => "computer"),
            "ERA_ATOMIC" => array("libelle" => "Ére atomique","icon" => "bomb"),
            "ERA_INFORMATION" => array("libelle" => "Ére de l'information","icon" => "server"),
            "ERA_FUTURE" => array("libelle" => "Ére futuriste","icon" => "robot"),
        );

        if(isset($array[$eraId]))
        {
            return $array[$eraId];
        }else{
            return("unknown");
        }
    } 

    include("index.html");

?>